import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";
import ResponsiveDrawer from "../components/ResponsiveDrawer";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Salloum Control Panel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const localeCookie = (await cookies()).get("locale")?.value;
  const locale = localeCookie === "en" ? "en" : "ar";
  const messages = locale === "ar"
    ? (await import("../messages/ar.json")).default
    : (await import("../messages/en.json")).default;

  return (
    <html lang={locale} dir="ltr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ margin: 0, padding: 0 }}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <ResponsiveDrawer>
              <main style={{ flex: 1, padding: 24, background: 'var(--background)', color: 'var(--foreground)' }}>
                {children}
              </main>
            </ResponsiveDrawer>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
